### ISSUE TITLE
AssertionError: Datasets are not equal in length.

### ISSUE THREAD

**Issue by NaeemKhan333** [PeterL1n/BackgroundMattingV2#47]
Thanks for nice work.I am running the file 'inference_images.py'

```
python inference_images.py --model-type=mattingrefine --model-backbone=resnet50 --model-backbone-scale 0.25 --model-refine-mode sampling --model-refine-sample-pixels 80000 --model-checkpoint=pytorch_resnet50.pth --images-src=myimages/ --images-bgr=back/ --device=cpu --output-dir=out/ --output-types=com

```
I am getting the following error 

```
Traceback (most recent call last):
  File "inference_images.py", line 108, in <module>
    A.PairApply(T.ToTensor())
  File "/home/mylaptop/Downloads/BackgroundMattingV2/dataset/zip.py", line 11, in __init__
    assert len(datasets[i]) == len(datasets[i - 1]), 'Datasets are not equal in length.'
AssertionError: Datasets are not equal in length.
```

**Comment by PeterL1n** [comment]
That tells you your `myimages/` and `back/` directories contain different numbers of images. They need to have the same amount of images to have a one-to-one correspondence.
