### ISSUE TITLE
用4K视频+inference_video.py 总是报错

### ISSUE THREAD

**Issue by zhanghonglishanzai** [PeterL1n/BackgroundMattingV2#97]
python /home/ubuntu/BM/BackgroundMattingV2/inference_video.py \
        --model-type mattingrefine \
        --model-backbone resnet50 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "/home/ubuntu/BM/pytorch_resnet50.pth" \
        --video-src "/home/ubuntu/BM/content/4K_pre-process/b5.mp4" \
        --video-bgr "/home/ubuntu/BM/content/4K_pre-process/b5.png" \
        --output-dir "/home/ubuntu/BM/content/4K_pre-process/output/" \
        --output-type com fgr pha err ref

`(modnet_offline_5) ubuntu@ubuntu:~/BM/content/4K_pre-process$ python /home/ubuntu/BM/BackgroundMattingV2/inference_video.py \
>         --model-type mattingrefine \
>         --model-backbone resnet50 \
>         --model-backbone-scale 0.25 \
>         --model-refine-mode sampling \
>         --model-refine-sample-pixels 80000 \
>         --model-checkpoint "/home/ubuntu/BM/pytorch_resnet50.pth" \
>         --video-src "/home/ubuntu/BM/content/4K_pre-process/b5.mp4" \
>         --video-bgr "/home/ubuntu/BM/content/4K_pre-process/b5.png" \
>         --output-dir "/home/ubuntu/BM/content/4K_pre-process/output/" \
>         --output-type com fgr pha err ref
 93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 359/388 [03:05<00:15,  1.93it/s]
Traceback (most recent call last):
  File "/home/ubuntu/BM/BackgroundMattingV2/inference_video.py", line 182, in <module>
    for input_batch in tqdm(DataLoader(dataset, batch_size=1, pin_memory=True)):
  File "/home/ubuntu/anaconda3/envs/modnet_offline_5/lib/python3.6/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/envs/modnet_offline_5/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/modnet_offline_5/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/anaconda3/envs/modnet_offline_5/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/modnet_offline_5/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/BM/BackgroundMattingV2/dataset/zip.py", line 17, in __getitem__
    x = tuple(d[idx % len(d)] for d in self.datasets)
  File "/home/ubuntu/BM/BackgroundMattingV2/dataset/zip.py", line 17, in <genexpr>
    x = tuple(d[idx % len(d)] for d in self.datasets)
  File "/home/ubuntu/BM/BackgroundMattingV2/dataset/video.py", line 27, in __getitem__
    raise IndexError(f'Idx: {idx} out of length: {len(self)}')
IndexError: Idx: 359 out of length: 388`

这个错误之前在其他人的issues中看到过，请问有解决方案了吗

**Comment by PeterL1n** [comment]
这个错误可以忽略，视频应该已经Export成功了。

**Comment by lzn1273180880** [comment]
您好，您后面还有遇到类似的问题吗，我也遇到这个错误，并且视频质量不是很好
